scan_filter_chain:
- name: laser_cutoff
  type: laser_filters/LaserScanAngularBoundsFilter
  params:
    lower_angle: -1.57079632679
    upper_angle: 1.57079632679
- name: interpolation
  type: laser_filters/InterpolationFilter
- name: range
  type: laser_filters/LaserScanRangeFilter
  params:
    lower_threshold: 0.3
    upper_threshold: .inf
